POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "1@Secured"
}
###
GET http://localhost:8080/tournament/get?tournamentName=iantest4

###
DELETE http://localhost:8080/tournament/delete?tournamentName=iantest4
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImI4Y2FjOTViNGE1YWNkZTBiOTY1NzJkZWU4YzhjOTVlZWU0OGNjY2QiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzE0NjI0NzgsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMTQ2MjQ3OCwiZXhwIjoxNzMxNDY2MDc4LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.X98N9dr3Rm6FH7mCptgpmqazCQtbyRXrNwTS1SGIS8nOe72c3icTUogykrBFW9Adj7BueyLu_1TGZOKsbIIgXh-TzrRsamyX5BA-Hy4Xy6yWADCvLPmY-XlYlLC5AlZHkGXebJ63ErRi2elxKjz2w-kpDAkjxepxE5kYKxxjDqKgEJXB3Rl9Sjznpd0vCd-VA4N9aKpljDV60UZb772yTe2OYo8d9JEKYQvTMVibIBshYc5T-V341QJfxqekeFir4xagfLteN2PQ1ok_LG_SE0bflbL51HtwkxvA87jNDtpBO9M4VT6E3O6h4lRNTOfXTF_BEHmr5-GSKWguB_Q20g
###
POST http://localhost:8080/tournament/player/create?tournamentName=iantest4&participatingPlayerName=user3
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImI4Y2FjOTViNGE1YWNkZTBiOTY1NzJkZWU4YzhjOTVlZWU0OGNjY2QiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzE0MTY3NDIsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMTQxNjc0MiwiZXhwIjoxNzMxNDIwMzQyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ouEqqdzvehQXJMQ_zAjO8xoypu0kjUkBHMbJj-fv-QE0Fo_yIingL8s2sfmcEnxeWPAae-Kkf_UGHViaghrj6JB4V0tD584v2GMmczk6P_6rBRvPkaLkjMI5aPbAKrFeJyf932TFyfNdEaf8IB9c_is1aI1MhJ152slm-tn6BglEAkDv_HaZRfkfRN67thAJaAx1_HgHfq7OnE8URxbI6o53f-u_Ql7kCB8ldoLEHIZl9AzI0A0LNN7sFe05iCzpb9O3FRcGxcty5ZKbdTqx-l6vUbrU6rYbDZB2YtBjwSmFyWcWMy6oSaW5AwAYiVJlSNAjmXlX2BcuSx3negGDIg

###
POST http://localhost:8080/tournament/start?tournamentName=iantest4
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImI4Y2FjOTViNGE1YWNkZTBiOTY1NzJkZWU4YzhjOTVlZWU0OGNjY2QiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzE0MTY3NDIsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMTQxNjc0MiwiZXhwIjoxNzMxNDIwMzQyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ouEqqdzvehQXJMQ_zAjO8xoypu0kjUkBHMbJj-fv-QE0Fo_yIingL8s2sfmcEnxeWPAae-Kkf_UGHViaghrj6JB4V0tD584v2GMmczk6P_6rBRvPkaLkjMI5aPbAKrFeJyf932TFyfNdEaf8IB9c_is1aI1MhJ152slm-tn6BglEAkDv_HaZRfkfRN67thAJaAx1_HgHfq7OnE8URxbI6o53f-u_Ql7kCB8ldoLEHIZl9AzI0A0LNN7sFe05iCzpb9O3FRcGxcty5ZKbdTqx-l6vUbrU6rYbDZB2YtBjwSmFyWcWMy6oSaW5AwAYiVJlSNAjmXlX2BcuSx3negGDIg

###
GET http://localhost:8080/tournament/round/match/player/get?tournamentName=iantest3&roundName=1&player=user1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImI4Y2FjOTViNGE1YWNkZTBiOTY1NzJkZWU4YzhjOTVlZWU0OGNjY2QiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzE0MTY3NDIsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMTQxNjc0MiwiZXhwIjoxNzMxNDIwMzQyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ouEqqdzvehQXJMQ_zAjO8xoypu0kjUkBHMbJj-fv-QE0Fo_yIingL8s2sfmcEnxeWPAae-Kkf_UGHViaghrj6JB4V0tD584v2GMmczk6P_6rBRvPkaLkjMI5aPbAKrFeJyf932TFyfNdEaf8IB9c_is1aI1MhJ152slm-tn6BglEAkDv_HaZRfkfRN67thAJaAx1_HgHfq7OnE8URxbI6o53f-u_Ql7kCB8ldoLEHIZl9AzI0A0LNN7sFe05iCzpb9O3FRcGxcty5ZKbdTqx-l6vUbrU6rYbDZB2YtBjwSmFyWcWMy6oSaW5AwAYiVJlSNAjmXlX2BcuSx3negGDIg

###
PUT http://localhost:8080/tournament/round/match/update?tournamentName=iantest4&roundName=1&player1=user3&player2=user2
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImI4Y2FjOTViNGE1YWNkZTBiOTY1NzJkZWU4YzhjOTVlZWU0OGNjY2QiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzE0MTY3NDIsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMTQxNjc0MiwiZXhwIjoxNzMxNDIwMzQyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ouEqqdzvehQXJMQ_zAjO8xoypu0kjUkBHMbJj-fv-QE0Fo_yIingL8s2sfmcEnxeWPAae-Kkf_UGHViaghrj6JB4V0tD584v2GMmczk6P_6rBRvPkaLkjMI5aPbAKrFeJyf932TFyfNdEaf8IB9c_is1aI1MhJ152slm-tn6BglEAkDv_HaZRfkfRN67thAJaAx1_HgHfq7OnE8URxbI6o53f-u_Ql7kCB8ldoLEHIZl9AzI0A0LNN7sFe05iCzpb9O3FRcGxcty5ZKbdTqx-l6vUbrU6rYbDZB2YtBjwSmFyWcWMy6oSaW5AwAYiVJlSNAjmXlX2BcuSx3negGDIg
Content-Type: application/json

{
    "player1": "user3",
    "player2": "user2",
    "winner": "user3",
    "wins": 2,
    "losses": 0,
    "bye": false,
    "draw": false
}

###
GET http://localhost:8080/tournament/round/end?tournamentName=iantest4&roundName=1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImI4Y2FjOTViNGE1YWNkZTBiOTY1NzJkZWU4YzhjOTVlZWU0OGNjY2QiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzE0NjI0NzgsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMTQ2MjQ3OCwiZXhwIjoxNzMxNDY2MDc4LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.X98N9dr3Rm6FH7mCptgpmqazCQtbyRXrNwTS1SGIS8nOe72c3icTUogykrBFW9Adj7BueyLu_1TGZOKsbIIgXh-TzrRsamyX5BA-Hy4Xy6yWADCvLPmY-XlYlLC5AlZHkGXebJ63ErRi2elxKjz2w-kpDAkjxepxE5kYKxxjDqKgEJXB3Rl9Sjznpd0vCd-VA4N9aKpljDV60UZb772yTe2OYo8d9JEKYQvTMVibIBshYc5T-V341QJfxqekeFir4xagfLteN2PQ1ok_LG_SE0bflbL51HtwkxvA87jNDtpBO9M4VT6E3O6h4lRNTOfXTF_BEHmr5-GSKWguB_Q20g

###
GET http://localhost:8080/tournament/round/start?tournamentName=iantest4
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImI4Y2FjOTViNGE1YWNkZTBiOTY1NzJkZWU4YzhjOTVlZWU0OGNjY2QiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzE0MTY3NDIsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMTQxNjc0MiwiZXhwIjoxNzMxNDIwMzQyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ouEqqdzvehQXJMQ_zAjO8xoypu0kjUkBHMbJj-fv-QE0Fo_yIingL8s2sfmcEnxeWPAae-Kkf_UGHViaghrj6JB4V0tD584v2GMmczk6P_6rBRvPkaLkjMI5aPbAKrFeJyf932TFyfNdEaf8IB9c_is1aI1MhJ152slm-tn6BglEAkDv_HaZRfkfRN67thAJaAx1_HgHfq7OnE8URxbI6o53f-u_Ql7kCB8ldoLEHIZl9AzI0A0LNN7sFe05iCzpb9O3FRcGxcty5ZKbdTqx-l6vUbrU6rYbDZB2YtBjwSmFyWcWMy6oSaW5AwAYiVJlSNAjmXlX2BcuSx3negGDIg


###
POST http://localhost:8080/tournament/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImI4Y2FjOTViNGE1YWNkZTBiOTY1NzJkZWU4YzhjOTVlZWU0OGNjY2QiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzE0MTY3NDIsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMTQxNjc0MiwiZXhwIjoxNzMxNDIwMzQyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ouEqqdzvehQXJMQ_zAjO8xoypu0kjUkBHMbJj-fv-QE0Fo_yIingL8s2sfmcEnxeWPAae-Kkf_UGHViaghrj6JB4V0tD584v2GMmczk6P_6rBRvPkaLkjMI5aPbAKrFeJyf932TFyfNdEaf8IB9c_is1aI1MhJ152slm-tn6BglEAkDv_HaZRfkfRN67thAJaAx1_HgHfq7OnE8URxbI6o53f-u_Ql7kCB8ldoLEHIZl9AzI0A0LNN7sFe05iCzpb9O3FRcGxcty5ZKbdTqx-l6vUbrU6rYbDZB2YtBjwSmFyWcWMy6oSaW5AwAYiVJlSNAjmXlX2BcuSx3negGDIg

{
    "tournamentName": "iantest4",
    "startDate": "2024-12-09",
    "endDate": "2024-12-16",
    "registrationDeadline": "2024-12-02",
    "numberOfPlayers": 0,
    "tournamentDesc": "hello world",
    "location": "One Infinite Loop, Cupertino, CA 95014, USA",
    "imageUrl":  null,
    "inProgress": false,
    "currentRound": "0",
    "expectedNumRounds": 0,
    "adminList": [],
    "participatingPlayers": []
}
