### Create Account
POST http://localhost:8080/user
Content-Type: application/json

{
    "userName": "garychia14",
    "name": "gary",
    "birthday": "10/10/2010",
    "email": "gary1@gmail.com",
    "gender": "male",
    "password": "1@Secured"
}

### Admin Login - Please avoid changing the pw
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "1@Secured"
}

### User Login - Please avoid changing the pw
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "1@Secured"
}

### User Get
GET http://localhost:8080/user
Content-Type: application/json,
Authorization: Bearer jwt_token_from_login

### User Update
PUT http://localhost:8080/user
Content-Type: application/json,
Authorization: Bearer jwt_token_from_login
{
    "userName": "onglai",
    "name": "ong lai",
    "birthday": "10/10/2010",
    "email": "onglai@gmail.com",
    "gender": "male"
}

###
POST http://localhost:8080/tournament/player/create?tournamentName=Eternal Weekend Test 30102024&participatingPlayerName=bob4
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzA3MjMwODQsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDcyMzA4NCwiZXhwIjoxNzMwNzI2Njg0LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.gTcDoeC3vD6OOXtYweEhtvcw-MqpfOIDRlRAe-jtYWjgmLIO9yXivq4BgWzZ3i5I-04I52i3dJdL9r7Se9yGLu3Emxej74upCXRtjMzuAO32gUfkfm7pbumZ76FGm-ABv_AKtBmKBqABnrDEUDZF1-l-vfZtStNsfq5Flk6ewP0ULoqkNP8vQpIhlA5vpOzRCm4cWENfwd1QNk5NivWFn0JdSFt50l3BtAw61LccBNYVU7AtJBwGWwXHisEUAeDELZKiYJ6jixdVtnAznYCXbn5Ty6i_NqEZbdjrQb08Td065lLgjsl8B9u8A6k58TQjuxGhmtynZueffJIgxEC6HA

###
GET http://localhost:8080/tournament/get?tournamentName=Eternal Weekend Test 30102024

###
GET http://localhost:8080/tournament/player/get/matches?tournamentName=Eternal Weekend Test 30102024&participatingPlayerName=bob1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzA3MjMwODQsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDcyMzA4NCwiZXhwIjoxNzMwNzI2Njg0LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.gTcDoeC3vD6OOXtYweEhtvcw-MqpfOIDRlRAe-jtYWjgmLIO9yXivq4BgWzZ3i5I-04I52i3dJdL9r7Se9yGLu3Emxej74upCXRtjMzuAO32gUfkfm7pbumZ76FGm-ABv_AKtBmKBqABnrDEUDZF1-l-vfZtStNsfq5Flk6ewP0ULoqkNP8vQpIhlA5vpOzRCm4cWENfwd1QNk5NivWFn0JdSFt50l3BtAw61LccBNYVU7AtJBwGWwXHisEUAeDELZKiYJ6jixdVtnAznYCXbn5Ty6i_NqEZbdjrQb08Td065lLgjsl8B9u8A6k58TQjuxGhmtynZueffJIgxEC6HA

###
PUT http://localhost:8080/tournament/round/match/update?tournamentName=Eternal Weekend Test 30102024&roundName=1&player1=bob4&player2=bob1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzA3MjMwODQsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDcyMzA4NCwiZXhwIjoxNzMwNzI2Njg0LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.gTcDoeC3vD6OOXtYweEhtvcw-MqpfOIDRlRAe-jtYWjgmLIO9yXivq4BgWzZ3i5I-04I52i3dJdL9r7Se9yGLu3Emxej74upCXRtjMzuAO32gUfkfm7pbumZ76FGm-ABv_AKtBmKBqABnrDEUDZF1-l-vfZtStNsfq5Flk6ewP0ULoqkNP8vQpIhlA5vpOzRCm4cWENfwd1QNk5NivWFn0JdSFt50l3BtAw61LccBNYVU7AtJBwGWwXHisEUAeDELZKiYJ6jixdVtnAznYCXbn5Ty6i_NqEZbdjrQb08Td065lLgjsl8B9u8A6k58TQjuxGhmtynZueffJIgxEC6HA
Content-Type: application/json

{
    "player1": "bob4",
    "player2": "bob1",
    "winner": "bob4",
    "wins": 2,
    "losses": 0,
    "bye": false,
    "draw": false
}

###
POST http://localhost:8080/tournament/start?tournamentName=Eternal Weekend Test 30102024
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzA3MjMwODQsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDcyMzA4NCwiZXhwIjoxNzMwNzI2Njg0LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.gTcDoeC3vD6OOXtYweEhtvcw-MqpfOIDRlRAe-jtYWjgmLIO9yXivq4BgWzZ3i5I-04I52i3dJdL9r7Se9yGLu3Emxej74upCXRtjMzuAO32gUfkfm7pbumZ76FGm-ABv_AKtBmKBqABnrDEUDZF1-l-vfZtStNsfq5Flk6ewP0ULoqkNP8vQpIhlA5vpOzRCm4cWENfwd1QNk5NivWFn0JdSFt50l3BtAw61LccBNYVU7AtJBwGWwXHisEUAeDELZKiYJ6jixdVtnAznYCXbn5Ty6i_NqEZbdjrQb08Td065lLgjsl8B9u8A6k58TQjuxGhmtynZueffJIgxEC6HA

###
GET http://localhost:8080/tournament/round/end?tournamentName=Eternal Weekend Test 30102024&roundName=1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzA3MjMwODQsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDcyMzA4NCwiZXhwIjoxNzMwNzI2Njg0LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.gTcDoeC3vD6OOXtYweEhtvcw-MqpfOIDRlRAe-jtYWjgmLIO9yXivq4BgWzZ3i5I-04I52i3dJdL9r7Se9yGLu3Emxej74upCXRtjMzuAO32gUfkfm7pbumZ76FGm-ABv_AKtBmKBqABnrDEUDZF1-l-vfZtStNsfq5Flk6ewP0ULoqkNP8vQpIhlA5vpOzRCm4cWENfwd1QNk5NivWFn0JdSFt50l3BtAw61LccBNYVU7AtJBwGWwXHisEUAeDELZKiYJ6jixdVtnAznYCXbn5Ty6i_NqEZbdjrQb08Td065lLgjsl8B9u8A6k58TQjuxGhmtynZueffJIgxEC6HA

###
GET http://localhost:8080/tournament/round/start?tournamentName=Eternal Weekend Test 30102024
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzA3MjMwODQsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDcyMzA4NCwiZXhwIjoxNzMwNzI2Njg0LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.gTcDoeC3vD6OOXtYweEhtvcw-MqpfOIDRlRAe-jtYWjgmLIO9yXivq4BgWzZ3i5I-04I52i3dJdL9r7Se9yGLu3Emxej74upCXRtjMzuAO32gUfkfm7pbumZ76FGm-ABv_AKtBmKBqABnrDEUDZF1-l-vfZtStNsfq5Flk6ewP0ULoqkNP8vQpIhlA5vpOzRCm4cWENfwd1QNk5NivWFn0JdSFt50l3BtAw61LccBNYVU7AtJBwGWwXHisEUAeDELZKiYJ6jixdVtnAznYCXbn5Ty6i_NqEZbdjrQb08Td065lLgjsl8B9u8A6k58TQjuxGhmtynZueffJIgxEC6HA




### User Update
DELETE http://localhost:8080/user
Content-Type: application/json,
Authorization: Bearer jwt_token_from_login

### GET all tournaments
GET http://localhost:8080/tournament/get/all
Content-Type: application/json

### GET standings
GET http://localhost:8080/tournament/round/standing/get/all?tournamentName=Overwatch 2&roundName=1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzA2MjU2MzgsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDYyNTYzOCwiZXhwIjoxNzMwNjI5MjM4LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.LuBrZlxGq4O87DmcFY9TTsUNHZHph1CmUR87XNC4l_mZM-MJCqpfgrBpn-vYPXgkG1wKjUWdcNiqx8n-oduvoZ5AONl1sZMc8-dvkPonoP20JuDmPyvXQr2ADSzJunmmYrkL3L8wdEXHspn0E39LrSXHtrC8NeGxmpFtRrSJoqFGpiJ72Xg1lijHB1EUoOPU9H6H_jVJCigYH1obOltDgr23U24RECQjpGjjMCnyxj99Ggr3tg1iYrDSA017sHUsIAxA-kLB1-7wKJBHXzvYhlk3AHnzG9F1wHUyA1t9iju-fQa2BkiQxp9x2ZGZkgzfFw-U7tXuhYLw7fXmt0xtHQ
###
GET http://localhost:8080/tournament/round/match/player/get?tournamentName=Eternal Weekend Test 24102024&roundName=1&player=gary
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzAzNTQwNzgsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDM1NDA3OCwiZXhwIjoxNzMwMzU3Njc4LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.A9KImfgR_jkRleA6Od7FNuUY2sW-w-mkMvbqHaU0UnZ2WOOGddg7Fn1Rnn2ZHCTDq2jNfP5tUDLcUhF5am_e1VBDTXHZIKEVQpwsgflit7SUd8Vx4aM06f4GKBIBgWQLDfESLHfllqoe7f2FkblAutof5Hm6Msj5N-dA9c55-paWSZ4nF8mbRoAOlM-UlMc4-FYVZNIzrpbWMUmU4unshHComM-Zf-PvQQ0_YW053CrmQSaLIorzN_VwwmW9Jc66FO3OHmNPlKcdbNmn3dDAgY_JWQUVReTrp1ds1Drty_YkWTxVVSJvyVeO-iCLGueqA6bbfP6emM75whxH2pP55A

### GET round
GET http://localhost:8080/tournament/round/get?tournamentName=Peter Tournament&roundName=null
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzA1MzIyMzEsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDUzMjIzMSwiZXhwIjoxNzMwNTM1ODMxLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.fTrSob3116iJRj3pM-UJCGz9ata3fAvR16tCQ0NOsUPZZ355oL0ORylRDdhoexFaw7YLWcfTE9dTrQaJ7cwQxPsGtrANpr1vRe2u7vFYLeeU7AREI8-j3yaiIg509o4la7Hg_cVYD_2Vcfxi4l3DaVCy5rQJVlMxEsuf12vl6DIkdqzOI9M8PirMP1fjLw47oIJfoB_J4bWrqIIGMFEZGZpmvMziWWm2qOlVuowz2VskQ3ew818rg9u5sxHkUuo32Tq7GzjSKMrVQDtSzhUM2HRjvsT8Fza9hLveCpYcBsyr0ODwkaGagkoy6YZX0eoHRV10wkO4CY2K7EBHwCJp1w

POST http://localhost:8080/tournament/player/create?tournamentName=abc&participatingPlayerName=bob4
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzA1MzIyMzEsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDUzMjIzMSwiZXhwIjoxNzMwNTM1ODMxLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.fTrSob3116iJRj3pM-UJCGz9ata3fAvR16tCQ0NOsUPZZ355oL0ORylRDdhoexFaw7YLWcfTE9dTrQaJ7cwQxPsGtrANpr1vRe2u7vFYLeeU7AREI8-j3yaiIg509o4la7Hg_cVYD_2Vcfxi4l3DaVCy5rQJVlMxEsuf12vl6DIkdqzOI9M8PirMP1fjLw47oIJfoB_J4bWrqIIGMFEZGZpmvMziWWm2qOlVuowz2VskQ3ew818rg9u5sxHkUuo32Tq7GzjSKMrVQDtSzhUM2HRjvsT8Fza9hLveCpYcBsyr0ODwkaGagkoy6YZX0eoHRV10wkO4CY2K7EBHwCJp1w
###
GET http://localhost:8080/tournament/player/get?tournamentName=Overwatch 2&participatingPlayerName=user1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzA2MjU2MzgsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDYyNTYzOCwiZXhwIjoxNzMwNjI5MjM4LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.LuBrZlxGq4O87DmcFY9TTsUNHZHph1CmUR87XNC4l_mZM-MJCqpfgrBpn-vYPXgkG1wKjUWdcNiqx8n-oduvoZ5AONl1sZMc8-dvkPonoP20JuDmPyvXQr2ADSzJunmmYrkL3L8wdEXHspn0E39LrSXHtrC8NeGxmpFtRrSJoqFGpiJ72Xg1lijHB1EUoOPU9H6H_jVJCigYH1obOltDgr23U24RECQjpGjjMCnyxj99Ggr3tg1iYrDSA017sHUsIAxA-kLB1-7wKJBHXzvYhlk3AHnzG9F1wHUyA1t9iju-fQa2BkiQxp9x2ZGZkgzfFw-U7tXuhYLw7fXmt0xtHQ

GET http://localhost:8080/tournament/round/start?tournamentName=Commander’s Conclave
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzA1MzIyMzEsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDUzMjIzMSwiZXhwIjoxNzMwNTM1ODMxLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.fTrSob3116iJRj3pM-UJCGz9ata3fAvR16tCQ0NOsUPZZ355oL0ORylRDdhoexFaw7YLWcfTE9dTrQaJ7cwQxPsGtrANpr1vRe2u7vFYLeeU7AREI8-j3yaiIg509o4la7Hg_cVYD_2Vcfxi4l3DaVCy5rQJVlMxEsuf12vl6DIkdqzOI9M8PirMP1fjLw47oIJfoB_J4bWrqIIGMFEZGZpmvMziWWm2qOlVuowz2VskQ3ew818rg9u5sxHkUuo32Tq7GzjSKMrVQDtSzhUM2HRjvsT8Fza9hLveCpYcBsyr0ODwkaGagkoy6YZX0eoHRV10wkO4CY2K7EBHwCJp1w