### Create Account
POST http://localhost:8080/user
Content-Type: application/json

{
    "userName": "garychia14",
    "name": "gary",
    "birthday": "10/10/2010",
    "email": "gary1@gmail.com",
    "gender": "male",
    "password": "1@Secured"
}

### Admin Login - Please avoid changing the pw
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "1@Secured"
}

### User Login - Please avoid changing the pw
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "1@Secured"
}

### User Get
GET http://localhost:8080/user
Content-Type: application/json,
Authorization: Bearer jwt_token_from_login

### User Update
PUT http://localhost:8080/user
Content-Type: application/json,
Authorization: Bearer jwt_token_from_login
{
    "userName": "onglai",
    "name": "ong lai",
    "birthday": "10/10/2010",
    "email": "onglai@gmail.com",
    "gender": "male"
}

### User Update
DELETE http://localhost:8080/user
Content-Type: application/json,
Authorization: Bearer jwt_token_from_login

### GET all tournaments
GET http://localhost:8080/tournament/get/all
Content-Type: application/json



###
GET http://localhost:8080/tournament/round/match/player/get?tournamentName=Eternal Weekend Test 24102024&roundName=1&player=gary
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YWMzNTcyNzY3ZGUyNjE0ZmM1MTA4NjMzMDg3YTQ5MjMzMDNkM2IiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NzMjAzLWEyNjNiIiwiYXVkIjoiY3MyMDMtYTI2M2IiLCJhdXRoX3RpbWUiOjE3MzAzNDk3NDYsInVzZXJfaWQiOiJncWk3akNnd1M1WXo3N3hscm92aGQyeTBIaXMxIiwic3ViIjoiZ3FpN2pDZ3dTNVl6Nzd4bHJvdmhkMnkwSGlzMSIsImlhdCI6MTczMDM0OTc0NiwiZXhwIjoxNzMwMzUzMzQ2LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.QW43_qbmp63qCgMYEEnPi9pDmfA94_CvlOxH8r8VKBshi6ugPMMLO78S8xp0CTmknWAbOh-yNuFFCDKkh5s2WNwYWxz1tF0Bwrd_ii9mM32ryTG2biMkosgTCzJNiuCLlr5usbDpYi0x1HjPShivtLFUxzgCO-sHrKfwxoeO98PtK9UgCB4bOpF3iXsx1MAJ3G89HTk_vq9nkPW_MdYrO6G_Jv8s2vY24Ug7MA4X5ccBH2F_7zBiqyJOGqLBrdOlyaeD8G9PxZkBx93bvuhWRS4S_R9dlu-jSPCkAWOSs6esmawCl8g6Tyx1wo2tE_kn9SqKMMfEQdUhUh00qN3cuQ

